### ISSUE TITLE
Step 5.3: Restart

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#10]
A game isn’t much fun if you can only play it once. After the game ends, either with a win or a loss, make sure that the player can easily restart the game without needing to restart the entire program.

In this section you will:
**3. Update the GameBehaviorScript to produce a button at the end of the the game that restarts the game (returns everything to its original state)**

**Comment by lokijoanderso** [comment]
done.
