### ISSUE TITLE
Step 6.1: Extra Credit, Optional (Powerup items)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#11]
Once you have completed the above, you can move on to extra credit if you so choose. For extra credit you can add these elements covered in the textbook chapters 8 and 9, but not in this lab:

**Add at least one powerup items you can grab. Some ideas:**

1. Gain health
2. Extra damage from Blasts
3. Shield the play for some time
4. Extra speed
5. Anything else you can think!

Note: If you choose to add extra credit, add a README.txt in your root directory so we know what you added!
Another Note: No matter what you choose, you get up to 5 points extra credit. The lab is worth 50 total points. Focus on this last (if at all).

**Comment by lokijoanderso** [comment]
I think the next thing I'll try is to add an object to replenish marble health.
Unless you are already doing that... holler if you've started and I won't try to conflict with you. :-)

**Comment by lokijoanderso** [comment]
I also want to add something in the environment that makes use of jumping... maybe a goal at the top of a staircase or something?

**Comment by lokijoanderso** [comment]
Added health capsules. They work, but don't have fancy particles or movement yet.
Added ziggurat looking things that require the jumping mechanic to get health items.
