### ISSUE TITLE
Step 6.2: Extra Credit, Optional (Automate the Obstacles)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#12]
Once you have completed the above, you can move on to extra credit if you so choose. For extra credit you can add these elements covered in the textbook chapters 8 and 9, but not in this lab:

**Automate the Obstacles to move, beyond the basic script from last lab**.
     1. Patrol between specific points
     2. Pursue the Marble

Note: If you choose to add extra credit, add a README.txt in your root directory so we know what you added!
Another Note: No matter what you choose, you get up to 5 points extra credit. The lab is worth 50 total points. Focus on this last (if at all).

**Comment by jramtos** [comment]
The black ball (enemy) follows the marble. Decreases marble's health if touched.

**Comment by lokijoanderso** [comment]
Oh! Can you push?
I want to resolve any conflicts between what you did and what I'm working on... :-/
