### ISSUE TITLE
Step 6.3: Extra Credit, Optional (Other element from chapter 8/9)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#13]
Step 6: Extra Credit (Optional)

Once you have completed the above, you can move on to extra credit if you so choose. For extra credit you can add these elements covered in the textbook chapters 8 and 9, but not in this lab:

**Any other element from those chapters, upon approval from instructional staff.**

Note: If you choose to add extra credit, add a README.txt in your root directory so we know what you added!
Another Note: No matter what you choose, you get up to 5 points extra credit. The lab is worth 50 total points. Focus on this last (if at all).

**Comment by lokijoanderso** [comment]
Ideas:
* More stuff from issue #11 - shield... blast power ups.
* I kind of wanted to try changing the obstacle material as it gets hit so they look like they are cracking before they disappear.
* The default GUI elements are horrid. Given enough time, it would be nice to figure out how to make them better.
