### ISSUE TITLE
Step 7: Final Check List!

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#14]
- [x] Step 1: Jump

> - Enable the Marble to jump on a space bar press when close to the ground

- [x] Step 2: Projectiles
> - Create a Blast prefab
> - Enable the Marble to shoot Blasts on a mouse click
> - Ensure the blasts disappear some time after being shot

- [x] Step 3: Health and Game Management

- [x] Step 4: Game Text

- [x] Step 5: Win/Lose Conditions and Restart

- [x] Step 6: Extra Credit (Optional)
> - Create powerups.
> - Automate Obstacle motion
> -  Anything else from Chapters 8 and 9 with instructor approval

**Comment by lokijoanderso** [comment]
Leaving extra credit unchecked... but I think we can check it as long as what is working for me is also working on your end! :-)

**Comment by jramtos** [comment]
Works with me!
