### ISSUE TITLE
Step 3.3 : Health and Game Management (ObstacleBehavior script)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#5]
1. Create an ObstacleBehavior script to be applied to all the obstacles that decrements Obstacle health on contact with a Blast
2. Ensure that the Obstacle is deleted when its health is depleted

**Comment by jramtos** [comment]
Obstacle's health is set to 100.
Decreases by 50 on contact with a Blast

Functionality finished.

I wanted to include a particles effect after the obstacles are deleted (just as the goal) but I failed :/

**Comment by lokijoanderso** [comment]
There is this problem where if the particles are attached to the object and you destroy the object, they never appear.
I've messed around with the prefabs for our obstacles and made a high level empty object, then the obstacle body and particles on the same level of the hierarchy. Now when the particles are triggered, they can display even as the object's body is being destroyed by the script.

I kinda want to see if I can make a change to the material too... It would be neat if the obstacles crack at 50% and are destroyed at 100%... :-)
