### ISSUE TITLE
Step 4.1 : Game Text (Display the Marble’s health)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#6]
Now it will be hard to know how awesome or awful you are doing in the game without knowing your health, and how many goals you have collected. 
**Let’s add some text to the screen to let the user know how they are doing.**
In this section you will:

**1. Display the Marble’s health somewhere on screen**

**Comment by lokijoanderso** [comment]
I'm using the default GUI per the instructions in the book.

The boxes are really transparent and instructions to change them with GUI.skin.backgroundColor aren't working. So as a hack I triple layered the boxes. They are much easier to read now. 

I'm sure there must be a better way to deal with this... but will come back to it.
