### ISSUE TITLE
Step 4.2: Game Text (Display the Goals)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#7]
Now it will be hard to know how awesome or awful you are doing in the game without knowing your health, and how many goals you have collected. 
**Let’s add some text to the screen to let the user know how they are doing.**

In this section you will:

**2. Display the Goals collected, and how many remain**

**Comment by lokijoanderso** [comment]
This is done. Goals collected in upper left. Goals remain in banner across lower part of screen. Same as in the book... but with some hack-y formatting adjustments for legibility.
