### ISSUE TITLE
Step 5.2: Win/Lose Conditions and Restart (Trigger a Lose)

### ISSUE THREAD

**Issue by jramtos** [computers-for-learning-20/anderson_ramirez_HW5#9]
Now what kind of game is this if there are no winners or losers? Let’s change that. The rules are simple: get all the goals you win, lose all your health you lose.
Also, a game isn’t much fun if you can only play it once. After the game ends, either with a win or a loss, make sure that the player can easily restart the game without needing to restart the entire program.

In this section you will:
**2. Update the GameBehaviorScript to trigger a Lose screen when the Marble’s health is zero.**

**Comment by lokijoanderso** [comment]
done.
